/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentLanguage } from '../models/AgentLanguage';
import { OpenAI } from '../models/OpenAI';
import { Transcriber } from '../models/Transcriber';
import { Voice } from '../models/Voice';
import { Webhook } from '../models/Webhook';
import { HttpFile } from '../http/http';

export class AgentConfiguration {
    /**
    * The name of the agent
    */
    'name': string;
    /**
    * The initial message of the agent
    */
    'initialMessage': string;
    /**
    * The prompt of the agent
    */
    'prompt': string;
    /**
    * DO NOT USE! Deprecated!
    */
    'language'?: AgentLanguage;
    'languageModel'?: OpenAI;
    'voice'?: Voice;
    'transcriber'?: Transcriber;
    /**
    * The maximum call duration in seconds. If null, the call can be of any duration. The default value is 10 min.
    */
    'maxCallDuration'?: number;
    /**
    * The webhooks of the agent
    */
    'webhooks'?: Array<Webhook>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "initialMessage",
            "baseName": "initial_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "AgentLanguage",
            "format": ""
        },
        {
            "name": "languageModel",
            "baseName": "language_model",
            "type": "OpenAI",
            "format": ""
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "Voice",
            "format": ""
        },
        {
            "name": "transcriber",
            "baseName": "transcriber",
            "type": "Transcriber",
            "format": ""
        },
        {
            "name": "maxCallDuration",
            "baseName": "max_call_duration",
            "type": "number",
            "format": ""
        },
        {
            "name": "webhooks",
            "baseName": "webhooks",
            "type": "Array<Webhook>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}



