/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentLanguage } from '../models/AgentLanguage';
import { AgentResponse } from '../models/AgentResponse';
import { OpenAI } from '../models/OpenAI';
import { Transcriber } from '../models/Transcriber';
import { Voice } from '../models/Voice';
import { HttpFile } from '../http/http';

export class Agent {
    /**
    * The name of the agent
    */
    'name': any | null;
    /**
    * The initial message of the agent
    */
    'initialMessage': any | null;
    /**
    * The prompt of the agent
    */
    'prompt': any | null;
    /**
    * DO NOT USE! Deprecated!
    */
    'language'?: AgentLanguage;
    'languageModel'?: OpenAI;
    'voice'?: Voice;
    'transcriber'?: Transcriber;
    /**
    * The maximum call duration in seconds. If null, the call can be of any duration. The default value is 10 min.
    */
    'maxCallDuration'?: any | null;
    /**
    * The webhooks of the agent
    */
    'webhooks'?: any | null;
    /**
    * The id of the agent
    */
    'id': any | null;
    /**
    * The uri of the agent
    */
    'uri': any | null;
    /**
    * The id of the owner of the agent
    */
    'accountId': any | null;
    /**
    * The date and time the agent was created
    */
    'createdAt': any | null;
    /**
    * The date and time the agent was last updated
    */
    'updatedAt': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "any",
            "format": ""
        },
        {
            "name": "initialMessage",
            "baseName": "initial_message",
            "type": "any",
            "format": ""
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "any",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "AgentLanguage",
            "format": ""
        },
        {
            "name": "languageModel",
            "baseName": "language_model",
            "type": "OpenAI",
            "format": ""
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "Voice",
            "format": ""
        },
        {
            "name": "transcriber",
            "baseName": "transcriber",
            "type": "Transcriber",
            "format": ""
        },
        {
            "name": "maxCallDuration",
            "baseName": "max_call_duration",
            "type": "any",
            "format": ""
        },
        {
            "name": "webhooks",
            "baseName": "webhooks",
            "type": "any",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "any",
            "format": ""
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "any",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "any",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "any",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Agent.attributeTypeMap;
    }

    public constructor() {
    }
}



