/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum AgentLanguage {
    En = 'en',
    Fr = 'fr',
    Ja = 'ja',
    Es = 'es'
}
