/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OpenAI } from '../models/OpenAI';
import { Transcriber } from '../models/Transcriber';
import { Voice } from '../models/Voice';
import { Webhook } from '../models/Webhook';
import { HttpFile } from '../http/http';

export class AgentResponse {
    /**
    * The initial message that the agent will say. If null, the agent will wait for the user to speak first.
    */
    'initialMessage'?: string;
    /**
    * The prompt of the agent.
    */
    'prompt'?: string;
    'voice'?: Voice;
    'languageModel'?: OpenAI;
    'transcriber'?: Transcriber;
    /**
    * The maximum conversation duration in seconds. If null, the conversation can be of any duration. The default value is 10 min.
    */
    'maxDurationSeconds'?: number;
    /**
    * The webhooks of the agent. These are used for real-time conversation events such as function_calls, messages and much more.
    */
    'webhooks'?: Array<Webhook>;
    /**
    * The metadata of the agent. This is used to store additional information about the agent.
    */
    'metadata'?: { [key: string]: string; };
    /**
    * The uri of the agent.
    */
    'uri': string;
    /**
    * The id of the owner of the agent.
    */
    'accountId': string;
    /**
    * The date and time the agent was created.
    */
    'createdAt': Date;
    /**
    * The date and time the agent was last updated.
    */
    'updatedAt': Date;
    /**
    * The id of the agent.
    */
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "initialMessage",
            "baseName": "initial_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string",
            "format": ""
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "Voice",
            "format": ""
        },
        {
            "name": "languageModel",
            "baseName": "language_model",
            "type": "OpenAI",
            "format": ""
        },
        {
            "name": "transcriber",
            "baseName": "transcriber",
            "type": "Transcriber",
            "format": ""
        },
        {
            "name": "maxDurationSeconds",
            "baseName": "max_duration_seconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "webhooks",
            "baseName": "webhooks",
            "type": "Array<Webhook>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

