/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentProvider } from '../models/AgentProvider';
import { HttpFile } from '../http/http';

export class AgentCost {
    /**
    * The provider of the agent (i.e VoiceOS).
    */
    'provider': AgentProvider;
    /**
    * The cost for the agent usage (USD).
    */
    'cost': number;
    /**
    * The number of seconds used for the agent orchestration.
    */
    'seconds': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "AgentProvider",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "seconds",
            "baseName": "seconds",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentCost.attributeTypeMap;
    }

    public constructor() {
    }
}



