/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Model } from '../models/Model';
import { HttpFile } from '../http/http';

export class AzureVoice {
    /**
    * The voice provider.
    */
    'provider'?: AzureVoiceProviderEnum;
    'model'?: Model;
    /**
    * The pitch of the voice.
    */
    'pitch'?: number;
    /**
    * The rate of the voice.
    */
    'rate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "AzureVoiceProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Model",
            "format": ""
        },
        {
            "name": "pitch",
            "baseName": "pitch",
            "type": "number",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureVoice.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AzureVoiceProviderEnum {
    Azure = 'azure'
}

