/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum AzureLanguages {
    EnUs = 'en-US',
    FrFr = 'fr-FR',
    EsEs = 'es-ES',
    DeDe = 'de-DE',
    ItIt = 'it-IT',
    NlNl = 'nl-NL',
    PtBr = 'pt-BR',
    RuRu = 'ru-RU',
    JaJp = 'ja-JP',
    ZhCn = 'zh-CN',
    KoKr = 'ko-KR',
    ArSa = 'ar-SA',
    HiIn = 'hi-IN',
    IdId = 'id-ID',
    TrTr = 'tr-TR',
    UkUa = 'uk-UA',
    PlPl = 'pl-PL',
    SvSe = 'sv-SE',
    DaDk = 'da-DK',
    NbNo = 'nb-NO',
    FiFi = 'fi-FI',
    ViVn = 'vi-VN',
    ThTh = 'th-TH',
    CsCz = 'cs-CZ'
}
