/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum AzureModel {
    SteffanNeural = 'en-US-SteffanNeural',
    JennyNeural = 'en-US-JennyNeural',
    AndrewNeural = 'en-US-AndrewNeural',
    EmmaNeural = 'en-US-EmmaNeural',
    AvaNeural = 'en-US-AvaNeural',
    BrianNeural = 'en-US-BrianNeural',
    AvaMultilingualNeural = 'en-US-AvaMultilingualNeural',
    JennyMultilingualNeural = 'en-US-JennyMultilingualNeural',
    RyanMultilingualNeural = 'en-US-RyanMultilingualNeural',
    AndrewMultilingualNeural = 'en-US-AndrewMultilingualNeural',
    BrianMultilingualNeural = 'en-US-BrianMultilingualNeural',
    EmmaMultilingualNeural = 'en-US-EmmaMultilingualNeural',
    AlloyMultilingualNeural = 'en-US-AlloyMultilingualNeural',
    EchoMultilingualNeural = 'en-US-EchoMultilingualNeural',
    FableMultilingualNeural = 'en-US-FableMultilingualNeural',
    NovaMultilingualNeural = 'en-US-NovaMultilingualNeural',
    OnyxMultilingualNeural = 'en-US-OnyxMultilingualNeural',
    ShimmerMultilingualNeural = 'en-US-ShimmerMultilingualNeural'
}
