/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureModel } from '../models/AzureModel';
import { HttpFile } from '../http/http';

export class AzureSynthesizer {
    /**
    * The synthesizer provider.
    */
    'provider'?: AzureSynthesizerProviderEnum;
    /**
    * The azure model to use
    */
    'model'?: AzureModel;
    /**
    * The pitch of the voice
    */
    'pitch'?: number;
    /**
    * The rate of the voice
    */
    'rate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "AzureSynthesizerProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "AzureModel",
            "format": ""
        },
        {
            "name": "pitch",
            "baseName": "pitch",
            "type": "number",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureSynthesizer.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AzureSynthesizerProviderEnum {
    Azure = 'azure'
}

