/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureLanguages } from '../models/AzureLanguages';
import { HttpFile } from '../http/http';

export class AzureTranscriber {
    /**
    * The transcriber provider.
    */
    'provider'?: AzureTranscriberProviderEnum;
    /**
    * The selected languages for the transcription.
    */
    'languages'?: Array<AzureLanguages>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "AzureTranscriberProviderEnum",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<AzureLanguages>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AzureTranscriber.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AzureTranscriberProviderEnum {
    Azure = 'azure'
}

