/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BuyPhoneNumber {
    /**
    * The telephony provider.
    */
    'provider'?: BuyPhoneNumberProviderEnum;
    /**
    * The phone number to buy.
    */
    'phoneNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "BuyPhoneNumberProviderEnum",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuyPhoneNumber.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BuyPhoneNumberProviderEnum {
    Twilio = 'twilio'
}

