/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentCost } from '../models/AgentCost';
import { Currency } from '../models/Currency';
import { LanguageModelCost } from '../models/LanguageModelCost';
import { SynthesizerCost } from '../models/SynthesizerCost';
import { TelephonyCost } from '../models/TelephonyCost';
import { TranscriberCost } from '../models/TranscriberCost';
import { HttpFile } from '../http/http';

export class CallCost {
    /**
    * The total cost of the call.
    */
    'total': number;
    /**
    * The synthetizer cost.
    */
    'synthesizer': SynthesizerCost;
    /**
    * The transcriber cost.
    */
    'transcriber': TranscriberCost;
    /**
    * The language model cost.
    */
    'languageModel': LanguageModelCost;
    /**
    * The telephony cost. Returns null if the call was not a phone call.
    */
    'telephony'?: TelephonyCost;
    /**
    * The cost of the agent.
    */
    'agent': AgentCost;
    /**
    * The currency used. As of now, we only offer USD.
    */
    'currency'?: Currency;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "synthesizer",
            "baseName": "synthesizer",
            "type": "SynthesizerCost",
            "format": ""
        },
        {
            "name": "transcriber",
            "baseName": "transcriber",
            "type": "TranscriberCost",
            "format": ""
        },
        {
            "name": "languageModel",
            "baseName": "language_model",
            "type": "LanguageModelCost",
            "format": ""
        },
        {
            "name": "telephony",
            "baseName": "telephony",
            "type": "TelephonyCost",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "AgentCost",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallCost.attributeTypeMap;
    }

    public constructor() {
    }
}



