/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CallResponse } from '../models/CallResponse';
import { HttpFile } from '../http/http';

export class CallsPagination {
    /**
    * The list of conversations returned.
    */
    'items': Array<CallResponse>;
    /**
    * The current index of the page selected.
    */
    'index': number;
    /**
    * The total number of conversations.
    */
    'hasNext': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<CallResponse>",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "hasNext",
            "baseName": "has_next",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallsPagination.attributeTypeMap;
    }

    public constructor() {
    }
}

