/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CallRecording {
    /**
    * The recording url of the conversation.
    */
    'recordingUrl': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "recordingUrl",
            "baseName": "recording_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallRecording.attributeTypeMap;
    }

    public constructor() {
    }
}

