/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AgentConfiguration } from '../models/AgentConfiguration';
import { HttpFile } from '../http/http';

export class CreateCall {
    /**
    * The phone number associated with the account from which the call will be made.
    */
    'fromNumber': string;
    /**
    * The phone number to call including the country code.
    */
    'toNumber': string;
    /**
    * The agent id to use for the conversation. If null, the agent configuration will be used.
    */
    'agentId'?: string;
    /**
    * The agent configuration to use for the conversation. If null, the agent id will be used.
    */
    'agentConfig'?: AgentConfiguration;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fromNumber",
            "baseName": "from_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "toNumber",
            "baseName": "to_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "agentId",
            "baseName": "agent_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "agentConfig",
            "baseName": "agent_config",
            "type": "AgentConfiguration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCall.attributeTypeMap;
    }

    public constructor() {
    }
}

