/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Agent } from '../models/Agent';
import { HttpFile } from '../http/http';

export class CreateCall {
    'toNumber': string;
    'fromNumber': string;
    'agent': Agent;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "toNumber",
            "baseName": "to_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromNumber",
            "baseName": "from_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "Agent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateCall.attributeTypeMap;
    }

    public constructor() {
    }
}

