/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Model2 } from '../models/Model2';
import { HttpFile } from '../http/http';

export class DeepgramVoice {
    /**
    * The synthesizer provider.
    */
    'provider'?: DeepgramVoiceProviderEnum;
    'model'?: Model2;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "DeepgramVoiceProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Model2",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeepgramVoice.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DeepgramVoiceProviderEnum {
    Deepgram = 'deepgram'
}

