/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Language } from '../models/Language';
import { Model1 } from '../models/Model1';
import { HttpFile } from '../http/http';

export class DeepgramTranscriber {
    /**
    * The transcriber provider.
    */
    'provider'?: DeepgramTranscriberProviderEnum;
    'model'?: Model1;
    'language'?: Language;
    /**
    * Specific keywords you want to detect in the transcription. This is useful to correctly understand product or company names.
    */
    'keywords'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "DeepgramTranscriberProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Model1",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "Language",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeepgramTranscriber.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DeepgramTranscriberProviderEnum {
    Deepgram = 'deepgram'
}

