/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum DeepgramLanguages {
    En = 'en',
    Fr = 'fr',
    Es = 'es',
    De = 'de',
    It = 'it',
    Nl = 'nl',
    Pt = 'pt',
    Ru = 'ru',
    Ja = 'ja',
    Cs = 'cs',
    Da = 'da',
    El = 'el',
    Hi = 'hi',
    Id = 'id',
    Ko = 'ko',
    No = 'no',
    Pl = 'pl',
    Sv = 'sv',
    Tr = 'tr',
    Uk = 'uk'
}
