/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ElevenLabsModel } from '../models/ElevenLabsModel';
import { VoiceId } from '../models/VoiceId';
import { HttpFile } from '../http/http';

export class ElevenlabsVoice {
    /**
    * The voice provider.
    */
    'provider'?: ElevenlabsVoiceProviderEnum;
    'voiceId'?: VoiceId;
    /**
    * The model to use. Defaults to eleven_turbo_v2.
    */
    'modelId'?: ElevenLabsModel;
    /**
    * Optimize for latency.
    */
    'optimizeLatency'?: number;
    /**
    * Use speaker boost.
    */
    'useSpeakerBoost'?: boolean;
    /**
    * Boost the similarity of the generated audio to the input text.
    */
    'similarityBoost'?: number;
    /**
    * Control the stability of the generated audio.
    */
    'stability'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "ElevenlabsVoiceProviderEnum",
            "format": ""
        },
        {
            "name": "voiceId",
            "baseName": "voice_id",
            "type": "VoiceId",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "ElevenLabsModel",
            "format": ""
        },
        {
            "name": "optimizeLatency",
            "baseName": "optimize_latency",
            "type": "number",
            "format": ""
        },
        {
            "name": "useSpeakerBoost",
            "baseName": "use_speaker_boost",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "similarityBoost",
            "baseName": "similarity_boost",
            "type": "number",
            "format": ""
        },
        {
            "name": "stability",
            "baseName": "stability",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ElevenlabsVoice.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ElevenlabsVoiceProviderEnum {
    Elevenlabs = 'elevenlabs'
}

