/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum ElevenLabsModel {
    _21m00Tcm4TlvDq8ikWam = '21m00Tcm4TlvDq8ikWAM',
    _5Q0t7uMcjvnagumLfvZi = '5Q0t7uMcjvnagumLfvZi',
    _29vD33N1CtxCmqQrpohj = '29vD33N1CtxCmqQRPOHJ',
    _2EiwWnXFnvU5JabPnv8n = '2EiwWnXFnvU5JabPnv8n',
    Cyw3kZ02Hs0563khs1Fj = 'CYw3kZ02Hs0563khs1Fj',
    D38z5RcWu1voky8Ws1ja = 'D38z5RcWu1voky8WS1ja',
    Exavitqu4vr4xnSdxMaL = 'EXAVITQu4vr4xnSDxMaL'
}
