/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum EventName {
    PhoneCallconnectionRequested = 'phone_call:connection_requested',
    PhoneCallrejected = 'phone_call:rejected',
    PhoneCallaccepted = 'phone_call:accepted',
    FunctionCalltriggered = 'function_call:triggered',
    Conversationstarted = 'conversation:started',
    Conversationended = 'conversation:ended',
    Conversationduration = 'conversation:duration',
    Speechstarted = 'speech:started',
    Speechended = 'speech:ended',
    Messagesent = 'message:sent',
    Messagegenerated = 'message:generated'
}
