/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventName } from '../models/EventName';
import { EventVariableName } from '../models/EventVariableName';
import { HttpFile } from '../http/http';

/**
* The event that triggers the webhook
*/
export class Event {

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
    ];

    static getAttributeTypeMap() {
        return Event.attributeTypeMap;
    }

    public constructor() {
    }
}

