/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OpenAIFunctionParameter } from '../models/OpenAIFunctionParameter';
import { HttpFile } from '../http/http';

export class OpenAIFunction {
    /**
    * This is the name of the function to be called. Must be less than 64 characters (a-z, A-Z, 0-9, including underscores).
    */
    'name': string;
    /**
    * If true, the agent will wait for the function to return before continuing.
    */
    'wait'?: boolean;
    /**
    * The description of the OpenAI function call.
    */
    'description': string;
    /**
    * The parameters of the OpenAI function call.
    */
    'parameters': OpenAIFunctionParameter;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "wait",
            "baseName": "wait",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "OpenAIFunctionParameter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OpenAIFunction.attributeTypeMap;
    }

    public constructor() {
    }
}

