/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OpenAIFunctionType } from '../models/OpenAIFunctionType';
import { HttpFile } from '../http/http';

export class OpenAIFunctionParameter {
    /**
    * This must be set to \'object\'. It instructs the model to return a JSON object containing the function call properties.
    */
    'type'?: OpenAIFunctionType;
    /**
    * This provides a description of the properties required by the function.
    */
    'properties': any;
    /**
    * This specifies the properties that are required by the function.
    */
    'required'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "OpenAIFunctionType",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "any",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OpenAIFunctionParameter.attributeTypeMap;
    }

    public constructor() {
    }
}



