/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Model3 } from '../models/Model3';
import { HttpFile } from '../http/http';

export class OpenAI {
    /**
    * The language model provider.
    */
    'provider'?: OpenAIProviderEnum;
    'model'?: Model3;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "OpenAIProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Model3",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OpenAI.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum OpenAIProviderEnum {
    Openai = 'openai'
}

