/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TwilioTelephony } from '../models/TwilioTelephony';
import { HttpFile } from '../http/http';

export class PhoneNumberResponse {
    /**
    * The uri of the phone number.
    */
    'uri': string;
    /**
    * The agent uri that will be used for inbound calls. If null, the phone number is will not receive any calls.
    */
    'inboundAgentUri'?: string;
    /**
    * The phone number.
    */
    'phoneNumber': string;
    /**
    * The account id associated with the phone number.
    */
    'accountId': string;
    /**
    * The date the phone number was created.
    */
    'createdAt': Date;
    /**
    * The date the phone number was last updated.
    */
    'updatedAt': Date;
    /**
    * The telephony of the phone number.
    */
    'telephony': TwilioTelephony;
    /**
    * The stripe subscription id of the phone number. Returns null if the phone number was imported.
    */
    'stripeSubscriptionId'?: string;
    /**
    * The id of the phone number.
    */
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string",
            "format": ""
        },
        {
            "name": "inboundAgentUri",
            "baseName": "inbound_agent_uri",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "telephony",
            "baseName": "telephony",
            "type": "TwilioTelephony",
            "format": ""
        },
        {
            "name": "stripeSubscriptionId",
            "baseName": "stripe_subscription_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PhoneNumberResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

