/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum PlayHTModel {
    Susan = 'susan',
    William = 'william',
    Phoebe = 'phoebe',
    Arthur = 'arthur',
    Ayla = 'ayla',
    Dylan = 'dylan',
    Madelyn = 'madelyn',
    Oliver = 'oliver',
    Sophia = 'sophia'
}
