/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Model4 } from '../models/Model4';
import { HttpFile } from '../http/http';

export class PlayhtVoice {
    /**
    * The voice provider.
    */
    'provider'?: PlayhtVoiceProviderEnum;
    'model'?: Model4;
    /**
    * Control how fast the generated audio should be. A number greater than 0 and less than or equal to 5.0
    */
    'speed'?: number;
    /**
    * A floating point number between 0, inclusive, and 2, inclusive. If equal to null or not provided, the model\'s default temperature will be used.
    */
    'temperature'?: number;
    /**
    * A number between 1 and 2. This number influences how closely the generated speech adheres to the input text.
    */
    'textGuidance'?: number;
    /**
    * A number between 1 and 30. Use lower numbers to to reduce how strong your chosen emotion will be. Higher numbers will create a very emotional performance.
    */
    'styleGuidance'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "PlayhtVoiceProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Model4",
            "format": ""
        },
        {
            "name": "speed",
            "baseName": "speed",
            "type": "number",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": ""
        },
        {
            "name": "textGuidance",
            "baseName": "text_guidance",
            "type": "number",
            "format": ""
        },
        {
            "name": "styleGuidance",
            "baseName": "style_guidance",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayhtVoice.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PlayhtVoiceProviderEnum {
    Playht = 'playht'
}

