/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Speaker } from '../models/Speaker';
import { HttpFile } from '../http/http';

export class RimeVoice {
    /**
    * The voice provider.
    */
    'provider'?: RimeVoiceProviderEnum;
    'speaker'?: Speaker;
    /**
    * Adjusts the speed of speech. Lower than 1.0 is faster than default. Higher than 1.0 is slower than default.
    */
    'speedAlpha'?: number;
    /**
    * Reduces the latency of response, at the cost of some possible mispronunciation of digits and abbreviations.
    */
    'reduceLatency'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "RimeVoiceProviderEnum",
            "format": ""
        },
        {
            "name": "speaker",
            "baseName": "speaker",
            "type": "Speaker",
            "format": ""
        },
        {
            "name": "speedAlpha",
            "baseName": "speed_alpha",
            "type": "number",
            "format": ""
        },
        {
            "name": "reduceLatency",
            "baseName": "reduce_latency",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RimeVoice.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RimeVoiceProviderEnum {
    Rime = 'rime'
}

