/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum RimeSpeaker {
    Abbie = 'abbie',
    Allison = 'allison',
    Ally = 'ally',
    Alona = 'alona',
    Amber = 'amber',
    Ana = 'ana',
    Antoine = 'antoine',
    Armon = 'armon',
    Brenda = 'brenda',
    Brittany = 'brittany',
    Carol = 'carol',
    Colin = 'colin',
    Courtney = 'courtney',
    Elena = 'elena',
    Elliot = 'elliot',
    Eva = 'eva',
    Geoff = 'geoff',
    Gerald = 'gerald',
    Hank = 'hank',
    Helen = 'helen',
    Hera = 'hera',
    Jen = 'jen',
    Joe = 'joe',
    Joy = 'joy',
    Juan = 'juan',
    Kendra = 'kendra',
    Kendrick = 'kendrick',
    Kenneth = 'kenneth',
    Kevin = 'kevin',
    Kris = 'kris',
    Linda = 'linda',
    Madison = 'madison',
    Marge = 'marge',
    Marina = 'marina',
    Marissa = 'marissa',
    Marta = 'marta',
    Maya = 'maya',
    Nicholas = 'nicholas',
    Nyles = 'nyles',
    Phil = 'phil',
    Reba = 'reba',
    Rex = 'rex',
    Rick = 'rick',
    Ritu = 'ritu',
    Rob = 'rob',
    Rodney = 'rodney',
    Rohan = 'rohan',
    Rosco = 'rosco',
    Samantha = 'samantha',
    Sandy = 'sandy',
    Selena = 'selena',
    Seth = 'seth',
    Sharon = 'sharon',
    Stan = 'stan',
    Tamra = 'tamra',
    Tanya = 'tanya',
    Tibur = 'tibur',
    Tj = 'tj',
    Tyler = 'tyler',
    Viv = 'viv',
    Yadira = 'yadira'
}
