/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WakoApiModelsPhoneNumberProvider } from '../models/WakoApiModelsPhoneNumberProvider';
import { HttpFile } from '../http/http';

export class TelephonyCost {
    /**
    * The provider of the phone number used.
    */
    'provider': WakoApiModelsPhoneNumberProvider;
    /**
    * The cost for the telephony usage. Returns zero, if the phone number was imported.
    */
    'cost': number;
    /**
    * The number of seconds used for the telephony.
    */
    'seconds': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "WakoApiModelsPhoneNumberProvider",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "seconds",
            "baseName": "seconds",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TelephonyCost.attributeTypeMap;
    }

    public constructor() {
    }
}



