/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WakoApiModelsTranscriberProvider } from '../models/WakoApiModelsTranscriberProvider';
import { HttpFile } from '../http/http';

export class TranscriberCost {
    /**
    * The provider of the transcriber.
    */
    'provider': WakoApiModelsTranscriberProvider;
    /**
    * The cost for the synthetizer usage. Returns zero, if the provider account you provided was used.
    */
    'cost': number;
    /**
    * The number of minutes used for the transcriber.
    */
    'seconds': number;
    /**
    * Whether the provider account you provided was used. If true, the cost will be zero.
    */
    'external': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "WakoApiModelsTranscriberProvider",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "seconds",
            "baseName": "seconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "external",
            "baseName": "external",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TranscriberCost.attributeTypeMap;
    }

    public constructor() {
    }
}



