/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureTranscriber } from '../models/AzureTranscriber';
import { DeepgramLanguages } from '../models/DeepgramLanguages';
import { DeepgramModel } from '../models/DeepgramModel';
import { DeepgramTranscriber } from '../models/DeepgramTranscriber';
import { HttpFile } from '../http/http';

export class Transcriber {
    /**
    * The transcriber provider.
    */
    'provider'?: TranscriberProviderEnum | null;
    /**
    * The deepgram model to use.
    */
    'model'?: DeepgramModel;
    /**
    * The selected language for the transcription.
    */
    'language'?: DeepgramLanguages;
    /**
    * Specific keywords you want to detect in the transcription. This is usefull to correctly understand product or company names.
    */
    'keywords'?: any | null;
    /**
    * The selected languages for the transcription.
    */
    'languages'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "TranscriberProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "DeepgramModel",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "DeepgramLanguages",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "any",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transcriber.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TranscriberProviderEnum {
    Azure = 'azure'
}

