/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AzureTranscriber } from '../models/AzureTranscriber';
import { DeepgramTranscriber } from '../models/DeepgramTranscriber';
import { Language } from '../models/Language';
import { Model1 } from '../models/Model1';
import { HttpFile } from '../http/http';

/**
* The transcriber of the agent.
*/
export class Transcriber1 {
    /**
    * The transcriber provider.
    */
    'provider'?: Transcriber1ProviderEnum | null;
    'model'?: Model1;
    'language'?: Language;
    /**
    * Specific keywords you want to detect in the transcription. This is useful to correctly understand product or company names.
    */
    'keywords'?: any | null;
    /**
    * The selected languages for the transcription.
    */
    'languages'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "Transcriber1ProviderEnum",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "Model1",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "Language",
            "format": ""
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "any",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Transcriber1.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum Transcriber1ProviderEnum {
    Azure = 'azure'
}

