/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdatePhoneNumber {
    /**
    * The agent uri that will be used for inbound calls. If null, the phone number is will not receive any calls.
    */
    'inboundAgentUri'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inboundAgentUri",
            "baseName": "inbound_agent_uri",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdatePhoneNumber.attributeTypeMap;
    }

    public constructor() {
    }
}

