/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WakoApiModelsSynthesizerProvider } from '../models/WakoApiModelsSynthesizerProvider';
import { HttpFile } from '../http/http';

export class VoiceCost {
    /**
    * The provider of the synthetizer.
    */
    'provider': WakoApiModelsSynthesizerProvider;
    /**
    * The cost for the voice usage (USD).
    */
    'cost': number;
    /**
    * The number of characters used for the voice.
    */
    'characters': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "WakoApiModelsSynthesizerProvider",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VoiceCost.attributeTypeMap;
    }

    public constructor() {
    }
}



