/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum WakoApiModelsSynthesizerDeepgramModel {
    AsteriaEn = 'aura-asteria-en',
    LunaEn = 'aura-luna-en',
    StellaEn = 'aura-stella-en',
    AthenaEn = 'aura-athena-en',
    HeraEn = 'aura-hera-en',
    OrionEn = 'aura-orion-en',
    ArcasEn = 'aura-arcas-en',
    PerseusEn = 'aura-perseus-en',
    AngusEn = 'aura-angus-en',
    OrpheusEn = 'aura-orpheus-en',
    HeliosEn = 'aura-helios-en',
    ZeusEn = 'aura-zeus-en'
}
