/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An enumeration.
*/
export enum WakoApiModelsTranscriberDeepgramModel {
    _2 = 'nova-2',
    _2General = 'nova-2-general',
    _2Meeting = 'nova-2-meeting',
    _2Phonecall = 'nova-2-phonecall',
    _2Finance = 'nova-2-finance',
    _2Voicemail = 'nova-2-voicemail',
    _2Medical = 'nova-2-medical',
    _2Drivethru = 'nova-2-drivethru',
    _2Automotive = 'nova-2-automotive',
    _2Conversationalai = 'nova-2-conversationalai'
}
