/**
 * VoiceOS
 * VoiceOS API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Event } from '../models/Event';
import { MethodEnum } from '../models/MethodEnum';
import { HttpFile } from '../http/http';

export class Webhook {
    'event': Event;
    /**
    * The url to call when the event is triggered
    */
    'url': string;
    /**
    * The method to use when calling the url
    */
    'method': MethodEnum;
    /**
    * The headers to use when calling the url
    */
    'headers'?: { [key: string]: string; };
    /**
    * The filter to use when triggering the webhook
    */
    'filter'?: { [key: string]: number; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "Event",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "MethodEnum",
            "format": ""
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "{ [key: string]: number; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Webhook.attributeTypeMap;
    }

    public constructor() {
    }
}



